// packages/autotel-devtools/src/widget/Widget.tsx
import { h, render } from 'preact'
import { useEffect } from 'preact/hooks'
import { DevtoolsWebSocketClient } from './websocket'
import { updateWidgetData, loadPersistedState, connectionStatusSignal } from './store'
import { Bubble } from './components/Bubble'
import { Panel } from './components/Panel'
import { Layout } from './components/Layout'

export { connectionStatusSignal }

interface WidgetProps {
  mode: 'widget' | 'fullpage'
  wsUrl: string
}

let wsClient: DevtoolsWebSocketClient | null = null

export function Widget({ mode, wsUrl }: WidgetProps) {
  useEffect(() => {
    loadPersistedState()

    wsClient = new DevtoolsWebSocketClient(wsUrl)
    connectionStatusSignal.value = 'connecting'

    wsClient.connect().then((connected) => {
      connectionStatusSignal.value = connected ? 'connected' : 'disconnected'
    })

    const unsubscribe = wsClient.onMessage((data) => {
      updateWidgetData(data)
      connectionStatusSignal.value = 'connected'
    })

    return () => {
      unsubscribe()
      wsClient?.disconnect()
      wsClient = null
    }
  }, [wsUrl])

  if (mode === 'fullpage') {
    return <Layout />
  }

  return (
    <>
      <Bubble />
      <Panel />
    </>
  )
}

export function mountWidget(container: HTMLElement | ShadowRoot, props: WidgetProps): () => void {
  render(h(Widget, props), container)
  return () => render(null, container)
}

// packages/autotel-devtools/src/widget/Widget.svelte
<script lang="ts">
  import { DevtoolsWebSocketClient } from './websocket';
  import {
    updateWidgetData,
    loadPersistedState,
    connectionStatusSignal,
    tracesSignal,
    pendingDeepLinkSignal,
    requestDeepLink,
    setSelectedTrace,
    setSelectedTab,
  } from './store.svelte';
  import Bubble from './components/Bubble.svelte';
  import Panel from './components/Panel.svelte';
  import Layout from './components/Layout.svelte';

  interface Props {
    mode: 'widget' | 'fullpage';
    wsUrl: string;
    deepLink?: { traceId: string; spanId?: string };
  }
  let { mode, wsUrl, deepLink }: Props = $props();

  // Register an inbound deep-link (e.g. from the VS Code extension's URL hash).
  $effect(() => {
    if (deepLink) requestDeepLink(deepLink.traceId, deepLink.spanId);
  });

  // Apply the pending deep-link once its trace has arrived over the wire.
  $effect(() => {
    const target = pendingDeepLinkSignal.value;
    if (!target) return;
    if (!tracesSignal.value.some((t) => t.traceId === target.traceId)) return;
    setSelectedTrace(target.traceId, target.spanId ?? null);
    setSelectedTab('traces');
    pendingDeepLinkSignal.value = null;
  });

  $effect(() => {
    loadPersistedState();

    const wsClient = new DevtoolsWebSocketClient(wsUrl);
    connectionStatusSignal.value = 'connecting';

    wsClient.connect().then((connected) => {
      connectionStatusSignal.value = connected ? 'connected' : 'disconnected';
    });

    const unsubscribe = wsClient.onMessage((data) => {
      updateWidgetData(data);
      connectionStatusSignal.value = 'connected';
    });

    return () => {
      unsubscribe();
      wsClient.disconnect();
    };
  });
</script>

{#if mode === 'fullpage'}
  <Layout />
{:else}
  <Bubble />
  <Panel />
{/if}
