// packages/autotel-devtools/src/widget/components/GenAiView.tsx
import { h } from 'preact'
import { useState } from 'preact/hooks'
import { Cpu, MessageSquare, Bot, List, Network } from 'lucide-preact'
import { genAiRowsSignal } from '../store'
import type { GenAiSpan } from '../genai/types'
import { ModelHeader } from './genai/ModelHeader'
import { ConversationPanel } from './genai/ConversationPanel'
import { AgentTimeline } from './genai/AgentTimeline'
import { cn } from '../utils/cn'

function formatLatency(ns: number): string {
  const ms = ns / 1_000_000
  if (ms < 1) return `${(ms * 1000).toFixed(0)}μs`
  if (ms < 1000) return `${ms.toFixed(0)}ms`
  return `${(ms / 1000).toFixed(2)}s`
}

function formatTokens(usage: GenAiSpan['usage']): string {
  const i = usage.inputTokens
  const o = usage.outputTokens
  if (i == null && o == null) return '—'
  return `${i ?? '—'}→${o ?? '—'}`
}

function formatCost(cost: GenAiSpan['cost']): string {
  if (!cost || cost.source === 'unknown') return '—'
  if (cost.total < 0.0001) return `$${(cost.total * 1_000_000).toFixed(2)}μ`
  if (cost.total < 0.01) return `$${(cost.total * 1000).toFixed(3)}m`
  return `$${cost.total.toFixed(4)}`
}

type Mode = 'list' | 'timeline'

export function GenAiView() {
  const rows = genAiRowsSignal.value
  const [selectedSpanId, setSelectedSpanId] = useState<string | null>(null)
  const [mode, setMode] = useState<Mode>('list')
  const selected = rows.find((r) => r.normalized.spanId === selectedSpanId) ?? rows[0]
  const hasConversations = rows.some((r) => r.normalized.conversationId)

  if (rows.length === 0) {
    return (
      <div className="p-6 text-sm text-zinc-500">
        <div className="flex items-center gap-2 mb-2 text-zinc-700 font-medium">
          <MessageSquare size={16} />
          No GenAI spans yet
        </div>
        <p>
          Spans appear here as soon as your app emits OpenTelemetry GenAI semconv
          attributes (any of <code className="text-xs">gen_ai.system</code>,{' '}
          <code className="text-xs">gen_ai.provider.name</code>, or{' '}
          <code className="text-xs">gen_ai.operation.name</code>). Works with
          Vercel AI SDK <code className="text-xs">experimental_telemetry</code>,
          Pydantic AI + Logfire, OpenAI Agents v2, Anthropic, Google GenAI,
          LangChain, OpenLLMetry — anything following the spec.
        </p>
      </div>
    )
  }

  if (mode === 'timeline') {
    return (
      <div className="flex flex-col h-full">
        <ModeToggle mode={mode} setMode={setMode} hasConversations={hasConversations} />
        <div className="flex-1 overflow-hidden">
          <AgentTimeline
            rows={rows}
            selectedSpanId={selected?.normalized.spanId ?? null}
            onSelectSpan={(id) => {
              setSelectedSpanId(id)
              setMode('list')
            }}
          />
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full">
      <ModeToggle mode={mode} setMode={setMode} hasConversations={hasConversations} />
      <div className="flex flex-1 overflow-hidden">
      <div className={cn('w-72 shrink-0 border-r border-zinc-200 overflow-y-auto')}>
        <ul className="divide-y divide-zinc-100">
          {rows.map((row) => {
            const active = row.normalized.spanId === selected?.normalized.spanId
            const errored = row.normalized.status === 'error'
            const model = row.normalized.responseModel ?? row.normalized.requestModel
            const isAgentSpan =
              row.normalized.agent?.name &&
              (row.normalized.provider === 'unknown' || model === 'unknown')
            return (
              <li key={row.normalized.spanId}>
                <button
                  type="button"
                  onClick={() => setSelectedSpanId(row.normalized.spanId)}
                  className={cn(
                    'w-full text-left px-3 py-2 hover:bg-zinc-50 transition-colors',
                    active && 'bg-zinc-100 hover:bg-zinc-100',
                  )}
                >
                  <div className="flex items-center gap-1.5 text-xs font-mono">
                    {isAgentSpan ? (
                      <Bot
                        size={11}
                        className={errored ? 'text-red-500' : 'text-violet-600'}
                      />
                    ) : (
                      <Cpu
                        size={11}
                        className={errored ? 'text-red-500' : 'text-zinc-500'}
                      />
                    )}
                    <span className="text-zinc-900 truncate">
                      {isAgentSpan
                        ? `agent: ${row.normalized.agent!.name}`
                        : `${row.normalized.provider}/${model}`}
                    </span>
                  </div>
                  <div className="mt-0.5 flex items-center gap-2 text-[11px] text-zinc-500">
                    <span>{row.normalized.operation}</span>
                    <span>·</span>
                    <span>{formatLatency(row.normalized.endNs - row.normalized.startNs)}</span>
                    <span>·</span>
                    <span>{formatTokens(row.normalized.usage)}</span>
                    <span className="ml-auto">{formatCost(row.normalized.cost)}</span>
                  </div>
                  {row.service && (
                    <div className="mt-0.5 text-[10px] text-zinc-400 truncate">
                      {row.service}
                    </div>
                  )}
                </button>
              </li>
            )
          })}
        </ul>
      </div>
      <div className="flex-1 overflow-y-auto">
        {selected && (
          <>
            <ModelHeader span={selected.normalized} />
            <ConversationPanel span={selected.normalized} />
          </>
        )}
      </div>
      </div>
    </div>
  )
}

function ModeToggle({
  mode,
  setMode,
  hasConversations,
}: {
  mode: Mode
  setMode: (m: Mode) => void
  hasConversations: boolean
}) {
  return (
    <div className="flex items-center gap-1 px-3 py-1.5 border-b border-zinc-200 bg-zinc-50/50">
      <button
        type="button"
        onClick={() => setMode('list')}
        className={cn(
          'inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium transition-colors',
          mode === 'list'
            ? 'bg-white border border-zinc-300 text-zinc-900 shadow-sm'
            : 'text-zinc-500 hover:text-zinc-700',
        )}
      >
        <List size={12} />
        List
      </button>
      <button
        type="button"
        onClick={() => setMode('timeline')}
        disabled={!hasConversations && false}
        className={cn(
          'inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium transition-colors',
          mode === 'timeline'
            ? 'bg-white border border-zinc-300 text-zinc-900 shadow-sm'
            : 'text-zinc-500 hover:text-zinc-700',
        )}
      >
        <Network size={12} />
        Timeline
        {!hasConversations && (
          <span className="ml-1 text-[10px] text-zinc-400">(by trace)</span>
        )}
      </button>
    </div>
  )
}

// packages/autotel-devtools/src/widget/components/GenAiView.svelte
<script lang="ts" module>
  import type { GenAiSpan } from '../genai/types';
  import { formatTokenCounts, formatCostUsd } from '../utils/genaiFormat';

  function formatLatency(ns: number): string {
    const ms = ns / 1_000_000;
    if (ms < 1) return `${(ms * 1000).toFixed(0)}μs`;
    if (ms < 1000) return `${ms.toFixed(0)}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  }

  function formatTokens(usage: GenAiSpan['usage']): string {
    return formatTokenCounts(usage.inputTokens, usage.outputTokens);
  }

  function formatCost(cost: GenAiSpan['cost']): string {
    return formatCostUsd(cost?.total, cost?.source === 'table');
  }

  type Mode = 'list' | 'timeline';

  function rowMatches(
    row: { normalized: GenAiSpan; service?: string },
    query: string,
  ): boolean {
    const n = row.normalized;
    return matchesNeedle(query.toLowerCase(), [
      n.responseModel ?? n.requestModel,
      n.requestModel,
      n.provider,
      String(n.operation),
      n.name,
      n.agent?.name,
      row.service,
    ]);
  }
</script>

<script lang="ts">
  import {
    Cpu,
    MessageSquare,
    Bot,
    List,
    Network,
    ExternalLink,
    ArrowLeft,
  } from '@lucide/svelte';
  import { genAiRowsSignal, openSpanInWaterfall } from '../store.svelte';
  import ModelHeader from './genai/ModelHeader.svelte';
  import ConversationPanel from './genai/ConversationPanel.svelte';
  import AgentTimeline from './genai/AgentTimeline.svelte';
  import SearchInput from './SearchInput.svelte';
  import { useListKeyboardNav } from './listNav.svelte';
  import { matchesNeedle } from '../utils/textMatch';
  import { cn } from '../utils/cn';

  const rows = $derived(genAiRowsSignal.value);
  let selectedSpanId = $state<string | null>(null);
  let mode = $state<Mode>('list');
  let query = $state('');
  const filtered = $derived.by(() =>
    rows.filter((row) => rowMatches(row, query)),
  );

  let rowEls = $state<(HTMLElement | null)[]>([]);

  const nav = useListKeyboardNav({
    count: () => filtered.length,
    // No row focused + Up jumps to the last span (Traces/Errors go to the first).
    fromUnsetUp: 'last',
    onActivate: (index) => {
      selectedSpanId = filtered[index].normalized.spanId;
    },
    scrollToIndex: (index) =>
      rowEls[index]?.scrollIntoView({ block: 'nearest' }),
  });
  const isFiltered = $derived(query.length > 0);
  const selected = $derived(
    filtered.find((r) => r.normalized.spanId === selectedSpanId) ??
      filtered[0] ??
      rows.find((r) => r.normalized.spanId === selectedSpanId) ??
      rows[0],
  );
  const hasConversations = $derived(
    rows.some((r) => r.normalized.conversationId),
  );
  // Single-column (narrow container) master/detail: the detail view replaces
  // the list only once the user has explicitly picked a span. `selected`
  // falls back to the first row for the side-by-side layout, so gate on the
  // explicit `selectedSpanId` here. Above the @md threshold both panes show
  // regardless and these utilities are no-ops.
  const mobileDetailOpen = $derived(selectedSpanId !== null);
</script>

{#snippet modeToggle()}
  <div
    class="flex items-center gap-1 px-3 py-1.5 border-b border-line bg-subtle/50"
  >
    <button
      type="button"
      onclick={() => (mode = 'list')}
      class={cn(
        'inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium transition-colors',
        mode === 'list'
          ? 'bg-surface border border-line text-fg shadow-sm'
          : 'text-fg-subtle hover:text-fg-muted',
      )}
    >
      <List size={12} />
      List
    </button>
    <button
      type="button"
      onclick={() => (mode = 'timeline')}
      disabled={!hasConversations && false}
      class={cn(
        'inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium transition-colors',
        mode === 'timeline'
          ? 'bg-surface border border-line text-fg shadow-sm'
          : 'text-fg-subtle hover:text-fg-muted',
      )}
    >
      <Network size={12} />
      Timeline
      {#if !hasConversations}
        <span class="ml-1 text-[10px] text-fg-subtle">(by trace)</span>
      {/if}
    </button>
  </div>
{/snippet}

{#if rows.length === 0}
  <div class="p-6 text-sm text-fg-subtle">
    <div class="flex items-center gap-2 mb-2 text-fg-muted font-medium">
      <MessageSquare size={16} />
      No GenAI spans yet
    </div>
    <p>
      Spans appear here as soon as your app emits OpenTelemetry GenAI semconv
      attributes (any of <code class="text-xs">gen_ai.system</code>,
      <code class="text-xs">gen_ai.provider.name</code>, or
      <code class="text-xs">gen_ai.operation.name</code>). Works with Vercel AI
      SDK <code class="text-xs">experimental_telemetry</code>, Pydantic AI +
      Logfire, OpenAI Agents v2, Anthropic, Google GenAI, LangChain, OpenLLMetry
      — anything following the spec.
    </p>
  </div>
{:else if mode === 'timeline'}
  <div class="flex flex-col h-full">
    {@render modeToggle()}
    <div class="flex-1 overflow-hidden">
      <AgentTimeline
        {rows}
        selectedSpanId={selected?.normalized.spanId ?? null}
        onSelectSpan={(id) => {
          selectedSpanId = id;
          mode = 'list';
        }}
      />
    </div>
  </div>
{:else}
  <div class="flex flex-col h-full">
    {@render modeToggle()}
    <!-- container-type: inline-size — collapse to a single column when the
         docked panel is narrow (right/left dock), no JS viewport hack. -->
    <div class="@container flex flex-1 overflow-hidden">
      <!-- Span list. Below the threshold it fills the width and hides while a
           span is open (single-column master/detail); above it is a fixed rail. -->
      <div
        class={cn(
          'flex flex-col w-full border-line @md:w-72 @md:shrink-0 @md:border-r',
          // In single-column mode, hide the list once a span is selected.
          mobileDetailOpen && 'hidden @md:flex',
        )}
      >
        {@render spanList()}
      </div>
      <!-- Detail. Below the threshold it is full-width and hidden until a span
           is selected; above it sits beside the rail. -->
      <div
        class={cn(
          'flex-1 overflow-y-auto w-full',
          !mobileDetailOpen && 'hidden @md:block',
        )}
      >
        {#if selected}
          <div class="flex items-center justify-between px-3 pt-2">
            <button
              type="button"
              onclick={() => (selectedSpanId = null)}
              class="@md:hidden inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[11px] text-fg-subtle hover:text-fg hover:bg-hover transition-colors"
            >
              <ArrowLeft size={11} />
              Back
            </button>
            <button
              type="button"
              onclick={() =>
                openSpanInWaterfall(
                  selected.traceId,
                  selected.normalized.spanId,
                )}
              class="ml-auto inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[11px] text-fg-subtle hover:text-fg hover:bg-hover transition-colors"
              title="Open this span in the Traces waterfall"
            >
              <ExternalLink size={11} />
              Open in Traces
            </button>
          </div>
          <ModelHeader span={selected.normalized} />
          <ConversationPanel span={selected.normalized} />
        {/if}
      </div>
    </div>
  </div>
{/if}

{#snippet spanList()}
  <div class="px-3 py-2 border-b border-line bg-subtle/50">
    <div class="text-[11px] font-medium text-fg-muted mb-1.5">
      Spans ({isFiltered ? `${filtered.length} of ${rows.length}` : rows.length})
    </div>
    <SearchInput
      bind:value={query}
      class=""
      inputClass="border-line bg-subtle text-fg focus:border-line focus:ring-1 focus:ring-accent"
      placeholder="Filter by model, operation, agent…"
      ariaLabel="Filter GenAI spans"
    />
  </div>
  <ul
    class="divide-y divide-line overflow-y-auto flex-1 focus:outline-none"
    tabindex="0"
    role="listbox"
    aria-label="GenAI spans"
    onkeydown={nav.onKeyDown}
  >
    {#if filtered.length === 0}
      <li class="px-3 py-6 text-xs text-fg-subtle text-center">No matches</li>
    {/if}
    {#each filtered as row, i (row.normalized.spanId)}
      {@const active = row.normalized.spanId === selected?.normalized.spanId}
      {@const errored = row.normalized.status === 'error'}
      {@const model =
        row.normalized.responseModel ?? row.normalized.requestModel}
      {@const isAgentSpan =
        row.normalized.agent?.name &&
        (row.normalized.provider === 'unknown' || model === 'unknown')}
      <li role="option" aria-selected={active}>
        <button
          type="button"
          bind:this={rowEls[i]}
          data-row-index={i}
          onclick={() => {
            nav.cursor = i;
            selectedSpanId = row.normalized.spanId;
          }}
          class={cn(
            'w-full text-left px-3 py-2 hover:bg-subtle transition-colors',
            active && 'bg-hover hover:bg-hover',
            i === nav.cursor && 'ring-1 ring-inset ring-accent bg-accent/10',
          )}
        >
          <div class="flex items-center gap-1.5 text-xs font-mono">
            {#if isAgentSpan}
              <Bot size={11} class={errored ? 'text-danger' : 'text-accent'} />
            {:else}
              <Cpu
                size={11}
                class={errored ? 'text-danger' : 'text-fg-subtle'}
              />
            {/if}
            <span class="text-fg truncate">
              {isAgentSpan
                ? `agent: ${row.normalized.agent!.name}`
                : `${row.normalized.provider}/${model}`}
            </span>
          </div>
          <div
            class="mt-0.5 flex items-center gap-2 text-[11px] text-fg-subtle"
          >
            <span>{row.normalized.operation}</span>
            <span>·</span>
            <span
              >{formatLatency(
                row.normalized.endNs - row.normalized.startNs,
              )}</span
            >
            <span>·</span>
            <span>{formatTokens(row.normalized.usage)}</span>
            <span class="ml-auto">{formatCost(row.normalized.cost)}</span>
          </div>
          {#if row.service}
            <div class="mt-0.5 text-[10px] text-fg-subtle truncate">
              {row.service}
            </div>
          {/if}
        </button>
      </li>
    {/each}
  </ul>
{/snippet}
