// packages/autotel-devtools/src/widget/components/TracesView.tsx
/**
 * Traces view - displays trace list and detailed trace viewer with waterfall visualization
 */

import { h } from 'preact';
import { useMemo, useState } from 'preact/hooks';
import {
  Database,
  Clock,
  AlertCircle,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  LayoutList,
  BarChart3,
  Flame,
  Download,
  Copy,
  Check,
  Pause,
  Play,
  Search,
  X,
} from 'lucide-preact';
import {
  sortedTracesSignal,
  selectedTraceSignal,
  setSelectedTrace,
  pausedSignal,
  pendingTraceCountSignal,
  togglePaused,
  dropPendingBuffer,
} from '../store';
import { formatDuration, formatTimestamp, getStatusColor } from '../utils';
import { cn } from '../utils/cn';
import { Copyable } from './Copyable';
import { WaterfallView } from './WaterfallView';
import { FlameGraphView } from './FlameGraphView';
import { SpanDetailPanel } from './SpanDetailPanel';
import {
  downloadTraceAsJson,
  copyTraceToClipboard,
  downloadTracesAsJson,
} from '../export-import';
import type { TraceData, SpanData } from '../types';

type ViewMode = 'waterfall' | 'flame' | 'list';
type StatusFilter = 'all' | 'error' | 'ok';

function traceMatches(
  trace: TraceData,
  query: string,
  status: StatusFilter,
): boolean {
  if (status === 'error' && trace.status !== 'ERROR') return false;
  if (status === 'ok' && trace.status === 'ERROR') return false;
  if (!query) return true;
  const needle = query.toLowerCase();
  if (trace.service?.toLowerCase().includes(needle)) return true;
  if (trace.rootSpan?.name?.toLowerCase().includes(needle)) return true;
  if (trace.traceId.toLowerCase().includes(needle)) return true;
  if (trace.correlationId?.toLowerCase().includes(needle)) return true;
  return trace.spans.some((span) => span.name?.toLowerCase().includes(needle));
}

export function TracesView() {
  const traces = sortedTracesSignal.value;
  const selectedTrace = selectedTraceSignal.value;
  const paused = pausedSignal.value;
  const pendingCount = pendingTraceCountSignal.value;
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');

  const filtered = useMemo(
    () => traces.filter((trace) => traceMatches(trace, query, statusFilter)),
    [traces, query, statusFilter],
  );

  if (selectedTrace) {
    return <TraceDetailView trace={selectedTrace} />;
  }

  const isFiltered = query.length > 0 || statusFilter !== 'all';

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-4 py-3 border-b border-zinc-200 flex items-center justify-between gap-2">
        <h3 className="text-sm font-semibold flex items-center gap-2 text-zinc-900">
          <Database size={16} />
          Traces ({isFiltered ? `${filtered.length} of ${traces.length}` : traces.length})
        </h3>
        <div className="flex items-center gap-1">
          <button
            onClick={togglePaused}
            className={cn(
              'flex items-center gap-1 px-2 py-1 text-xs rounded transition-colors',
              paused
                ? 'bg-amber-100 text-amber-800 hover:bg-amber-200'
                : 'hover:bg-zinc-100 text-zinc-600',
            )}
            title={paused ? 'Resume live tail' : 'Pause live tail'}
          >
            {paused ? <Play size={12} /> : <Pause size={12} />}
            {paused
              ? `Resume${pendingCount > 0 ? ` (+${pendingCount})` : ''}`
              : 'Pause'}
          </button>
          {paused && pendingCount > 0 && (
            <button
              onClick={dropPendingBuffer}
              className="px-2 py-1 text-xs rounded text-zinc-500 hover:bg-zinc-100 transition-colors"
              title="Drop buffered traces received while paused"
            >
              Drop buffer
            </button>
          )}
          {traces.length > 0 && (
            <button
              onClick={() => downloadTracesAsJson(traces)}
              className="p-1.5 hover:bg-zinc-100 rounded transition-colors"
              title="Export all traces as JSON"
            >
              <Download size={14} className="text-zinc-500" />
            </button>
          )}
        </div>
      </div>

      {/* Filter bar */}
      <div className="px-4 py-2 border-b border-zinc-200 flex items-center gap-2">
        <div className="relative flex-1">
          <Search
            size={12}
            className="absolute left-2 top-1/2 -translate-y-1/2 text-zinc-400"
          />
          <input
            value={query}
            onInput={(event) =>
              setQuery((event.currentTarget as HTMLInputElement).value)
            }
            className="w-full pl-7 pr-7 py-1 text-xs rounded border border-zinc-200 focus:border-zinc-400 focus:outline-none"
            placeholder="Filter by service, span, trace id…"
          />
          {query && (
            <button
              onClick={() => setQuery('')}
              className="absolute right-1 top-1/2 -translate-y-1/2 p-0.5 text-zinc-400 hover:text-zinc-700"
              title="Clear filter"
            >
              <X size={12} />
            </button>
          )}
        </div>
        <select
          value={statusFilter}
          onChange={(event) =>
            setStatusFilter(
              (event.currentTarget as HTMLSelectElement).value as StatusFilter,
            )
          }
          className="text-xs border border-zinc-200 rounded px-1.5 py-1 bg-white text-zinc-700"
        >
          <option value="all">All</option>
          <option value="error">Errors</option>
          <option value="ok">OK</option>
        </select>
      </div>

      {/* Traces list */}
      <div className="flex-1 overflow-auto p-4">
        {traces.length === 0 ? (
          <div className="text-center text-zinc-500 text-sm py-12">
            <p className="mb-3">No traces yet. Waiting for data...</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center text-zinc-500 text-sm py-12">
            No traces match the current filter.
          </div>
        ) : (
          <div className="space-y-2">
            {filtered.map((trace) => (
              <TraceRow
                key={trace.traceId}
                trace={trace}
                onClick={() => setSelectedTrace(trace.traceId)}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

interface TraceRowProps {
  trace: TraceData;
  onClick: () => void;
}

function TraceRow({ trace, onClick }: TraceRowProps) {
  const isError = trace.status === 'ERROR';

  return (
    <button
      onClick={onClick}
      className={cn(
        'w-full text-left p-3 rounded-md border transition-all',
        'hover:shadow-sm hover:border-zinc-300',
        isError
          ? 'bg-red-50 border-red-200 hover:border-red-300'
          : 'bg-white border-zinc-200 hover:border-zinc-300',
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1.5">
            <span className="font-mono text-xs text-zinc-500">
              {trace.correlationId}
            </span>
            {isError && (
              <AlertCircle size={14} className="text-red-600 flex-shrink-0" />
            )}
          </div>

          <div className="font-medium text-sm mb-2 truncate text-zinc-900">
            {trace.rootSpan.name || 'unknown'}
          </div>

          <div className="flex items-center gap-3 text-xs text-zinc-600 flex-wrap">
            <span className="flex items-center gap-1">
              <Clock size={12} />
              {formatDuration(trace.duration)}
            </span>
            <span>{trace.spans.length} spans</span>
            <span className={cn('font-medium', getStatusColor(trace.status))}>
              {trace.status}
            </span>
          </div>
        </div>

        <div className="flex flex-col items-end gap-1.5 flex-shrink-0">
          <span className="text-xs text-zinc-500">
            {formatTimestamp(trace.startTime)}
          </span>
          <ChevronRight size={16} className="text-zinc-400" />
        </div>
      </div>
    </button>
  );
}

interface TraceDetailViewProps {
  trace: TraceData;
}

function TraceDetailView({ trace }: TraceDetailViewProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('waterfall');
  const [selectedSpan, setSelectedSpan] = useState<SpanData | null>(null);
  const [copied, setCopied] = useState(false);

  const formatDate = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  };

  const handleDownload = () => {
    downloadTraceAsJson(trace);
  };

  const handleCopy = async () => {
    await copyTraceToClipboard(trace);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-4 py-3 border-b border-zinc-200">
        <div className="flex items-center justify-between mb-3">
          <button
            onClick={() => setSelectedTrace(null)}
            className={cn(
              'text-xs text-zinc-600 hover:text-zinc-900',
              'flex items-center gap-1 transition-colors',
            )}
          >
            <ChevronLeft size={14} />
            Back to traces
          </button>

          <div className="flex items-center gap-2">
            {/* Export buttons */}
            <div className="flex items-center gap-1">
              <button
                onClick={handleCopy}
                className="p-1.5 hover:bg-zinc-100 rounded transition-colors"
                title="Copy trace JSON to clipboard"
              >
                {copied ? (
                  <Check size={14} className="text-green-600" />
                ) : (
                  <Copy size={14} className="text-zinc-500" />
                )}
              </button>
              <button
                onClick={handleDownload}
                className="p-1.5 hover:bg-zinc-100 rounded transition-colors"
                title="Download trace as JSON"
              >
                <Download size={14} className="text-zinc-500" />
              </button>
            </div>

            {/* View mode toggle */}
            <div className="flex items-center gap-1 bg-zinc-100 rounded-md p-0.5">
              <button
                onClick={() => setViewMode('waterfall')}
                className={cn(
                  'px-2 py-1 text-xs rounded transition-colors flex items-center gap-1',
                  viewMode === 'waterfall'
                    ? 'bg-white text-zinc-900 shadow-sm'
                    : 'text-zinc-600 hover:text-zinc-900',
                )}
                title="Waterfall view"
              >
                <BarChart3 size={12} />
                Timeline
              </button>
              <button
                onClick={() => setViewMode('flame')}
                className={cn(
                  'px-2 py-1 text-xs rounded transition-colors flex items-center gap-1',
                  viewMode === 'flame'
                    ? 'bg-white text-zinc-900 shadow-sm'
                    : 'text-zinc-600 hover:text-zinc-900',
                )}
                title="Flame graph view"
              >
                <Flame size={12} />
                Flame
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={cn(
                  'px-2 py-1 text-xs rounded transition-colors flex items-center gap-1',
                  viewMode === 'list'
                    ? 'bg-white text-zinc-900 shadow-sm'
                    : 'text-zinc-600 hover:text-zinc-900',
                )}
                title="List view"
              >
                <LayoutList size={12} />
                List
              </button>
            </div>
          </div>
        </div>

        <div className="flex items-start justify-between gap-4">
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-base mb-1.5 text-zinc-900">
              {trace.rootSpan.name || 'Trace'}
            </h3>
            <div className="text-xs text-zinc-500 space-y-0.5">
              <div>{formatDate(trace.startTime)}</div>
              <div className="font-mono">Trace ID: {trace.traceId}</div>
            </div>
          </div>

          <div className="text-right flex-shrink-0">
            <div
              className={cn(
                'font-medium text-sm mb-1',
                getStatusColor(trace.status),
              )}
            >
              {trace.status}
            </div>
            <div className="text-xs text-zinc-600">
              {formatDuration(trace.duration)}
            </div>
            <div className="text-xs text-zinc-500 mt-1">
              {trace.spans.length} spans
            </div>
          </div>
        </div>
      </div>

      {/* Content area - flex row for waterfall + detail panel */}
      <div className="flex-1 overflow-hidden flex">
        {/* Main content */}
        <div
          className={cn(
            'flex-1 overflow-hidden',
            selectedSpan && 'border-r border-zinc-200',
          )}
        >
          {viewMode === 'waterfall' ? (
            <WaterfallView
              trace={trace}
              onSpanSelect={setSelectedSpan}
              selectedSpanId={selectedSpan?.spanId}
            />
          ) : viewMode === 'flame' ? (
            <FlameGraphView
              trace={trace}
              onSpanSelect={setSelectedSpan}
              selectedSpanId={selectedSpan?.spanId}
            />
          ) : (
            <div className="overflow-auto h-full">
              <div className="divide-y divide-zinc-100">
                {trace.spans.map((span) => (
                  <SpanRow
                    key={span.spanId}
                    span={span}
                    trace={trace}
                    isSelected={selectedSpan?.spanId === span.spanId}
                    onSelect={() => setSelectedSpan(span)}
                  />
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Span detail panel (right side) */}
        {selectedSpan && (
          <div className="w-[320px] flex-shrink-0 overflow-hidden">
            <SpanDetailPanel
              span={selectedSpan}
              trace={trace}
              onClose={() => setSelectedSpan(null)}
            />
          </div>
        )}
      </div>
    </div>
  );
}

interface SpanRowProps {
  span: SpanData;
  trace: TraceData;
  isSelected: boolean;
  onSelect: () => void;
}

function SpanRow({ span, trace, isSelected, onSelect }: SpanRowProps) {
  const [expanded, setExpanded] = useState(false);
  const [expandedSections, setExpandedSections] = useState<
    Record<string, boolean>
  >({
    attributes: false,
    events: false,
  });
  const isError = span.status.code === 'ERROR';

  const toggleSection = (section: string) => {
    setExpandedSections((prev) => ({ ...prev, [section]: !prev[section] }));
  };

  // Calculate indent level based on parent relationships
  const getIndentLevel = () => {
    let level = 0;
    let currentSpan = span;
    while (currentSpan.parentSpanId) {
      level++;
      const parent = trace.spans.find(
        (s) => s.spanId === currentSpan.parentSpanId,
      );
      if (!parent) break;
      currentSpan = parent;
    }
    return level;
  };

  const indentLevel = getIndentLevel();
  const hasAttributes = Object.keys(span.attributes || {}).length > 0;
  const hasEvents = span.events && span.events.length > 0;

  return (
    <div
      className={cn(
        'px-4 py-3',
        'hover:bg-zinc-50 transition-colors cursor-pointer',
        isError && 'bg-red-50/30',
        isSelected && 'bg-zinc-100 hover:bg-zinc-100',
      )}
      style={{ paddingLeft: `${16 + indentLevel * 20}px` }}
      onClick={onSelect}
    >
      <div className="flex items-center justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="font-medium text-sm mb-1 text-zinc-900">
            {span.name || 'unknown'}
          </div>
          <div className="flex items-center gap-3 text-xs text-zinc-600">
            <span
              className={cn('font-medium', getStatusColor(span.status.code))}
            >
              {span.status.code}
            </span>
            <span>{formatDuration(span.duration)}</span>
            <span className="text-zinc-400">{span.kind}</span>
          </div>
        </div>

        <button
          onClick={(e) => {
            e.stopPropagation();
            setExpanded(!expanded);
          }}
          className="p-1 hover:bg-zinc-200 rounded"
        >
          <ChevronDown
            size={14}
            className={cn(
              'text-zinc-400 transition-transform flex-shrink-0',
              expanded && 'rotate-180',
            )}
          />
        </button>
      </div>

      {expanded && (
        <div
          className="mt-3 pt-3 border-t border-zinc-200 space-y-3"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Attributes section */}
          {hasAttributes && (
            <ExpandableSection
              label="All attributes"
              expanded={expandedSections.attributes}
              onToggle={() => toggleSection('attributes')}
            >
              <Copyable content={JSON.stringify(span.attributes, null, 2)}>
                <div className="bg-zinc-50 rounded p-3 border border-zinc-200 font-mono text-xs">
                  <pre className="whitespace-pre-wrap break-words text-zinc-800">
                    {JSON.stringify(span.attributes, null, 2)}
                  </pre>
                </div>
              </Copyable>
            </ExpandableSection>
          )}

          {/* Events section */}
          {hasEvents && (
            <ExpandableSection
              label={`Events (${span.events!.length})`}
              expanded={expandedSections.events}
              onToggle={() => toggleSection('events')}
            >
              <div className="space-y-2">
                {span.events!.map((event, idx) => (
                  <div
                    key={idx}
                    className="bg-zinc-50 rounded p-2.5 border border-zinc-200"
                  >
                    <div className="font-medium text-xs text-zinc-900 mb-1.5">
                      {event.name}
                    </div>
                    {event.attributes &&
                      Object.keys(event.attributes).length > 0 && (
                        <Copyable
                          content={JSON.stringify(event.attributes, null, 2)}
                        >
                          <div className="font-mono text-xs text-zinc-600 mt-1">
                            {JSON.stringify(event.attributes, null, 2)}
                          </div>
                        </Copyable>
                      )}
                  </div>
                ))}
              </div>
            </ExpandableSection>
          )}

          {/* Status message */}
          {span.status.message && (
            <div className="text-xs text-zinc-600">
              <span className="font-medium">Status message:</span>{' '}
              {span.status.message}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

interface ExpandableSectionProps {
  label: string;
  expanded: boolean;
  onToggle: () => void;
  children: any;
}

function ExpandableSection({
  label,
  expanded,
  onToggle,
  children,
}: ExpandableSectionProps) {
  return (
    <div className="flex flex-col gap-2">
      <button
        onClick={onToggle}
        className="flex items-center gap-2 cursor-pointer text-zinc-700 hover:text-zinc-900 transition-colors w-fit"
      >
        <ChevronDown
          size={12}
          className={cn(
            'text-zinc-500 transition-transform',
            expanded && 'rotate-180',
          )}
        />
        <span className="text-xs font-medium">{label}</span>
      </button>
      {expanded && <div>{children}</div>}
    </div>
  );
}

// packages/autotel-devtools/src/widget/components/TracesView.svelte
<script lang="ts">
  /**
   * Traces view - displays trace list and detailed trace viewer with waterfall visualization
   */
  import {
    Database,
    AlertCircle,
    ChevronRight,
    Download,
    Pause,
    Play,
    HelpCircle,
    Trash2,
    Upload,
    ArrowUp,
    ArrowDown,
  } from '@lucide/svelte';
  import {
    sortedTracesSignal,
    selectedTraceSignal,
    setSelectedTrace,
    pausedSignal,
    pendingTraceCountSignal,
    togglePaused,
    dropPendingBuffer,
    selectedTraceIdsSignal,
    selectedTraceCountSignal,
    toggleTraceSelection,
    selectAllTraces,
    clearTraceSelection,
    deleteSelectedTraces,
    importTraces,
    helpShortcutsSignal,
    openHelp,
    traceSortSignal,
    setTraceSort,
  } from '../store.svelte';
  import type { TraceSortKey } from '../store.svelte';
  import { serviceColor } from '../utils/serviceColor';
  import { TRACE_LIST_SHORTCUTS } from '../shortcuts';
  import { formatDuration, formatTimestamp } from '../utils';
  import { cn } from '../utils/cn';
  import { isInputFocused, activateOnKey } from '../utils/keyboard';
  import TraceImportModal from './TraceImportModal.svelte';
  import TraceDetailView from './TraceDetailView.svelte';
  import CopyButton from './CopyButton.svelte';
  import SearchInput from './SearchInput.svelte';
  import { useListKeyboardNav } from './listNav.svelte';
  import { matchesNeedle } from '../utils/textMatch';
  import {
    readFileAsText,
    parseImportedJson,
    downloadTracesAsJson,
  } from '../export-import';
  import type { TraceData } from '../types';

  type StatusFilter = 'all' | 'error' | 'ok';

  function traceMatches(
    trace: TraceData,
    query: string,
    status: StatusFilter,
    minDurationMs: number,
  ): boolean {
    if (status === 'error' && trace.status !== 'ERROR') return false;
    if (status === 'ok' && trace.status === 'ERROR') return false;
    if (minDurationMs > 0 && trace.duration < minDurationMs) return false;
    return matchesNeedle(query.toLowerCase(), [
      trace.service,
      trace.rootSpan?.name,
      trace.traceId,
      trace.correlationId,
      ...trace.spans.map((span) => span.name),
    ]);
  }

  const traces = $derived(sortedTracesSignal.value);
  const sort = $derived(traceSortSignal.value);
  const selectedTrace = $derived(selectedTraceSignal.value);
  const paused = $derived(pausedSignal.value);
  const pendingCount = $derived(pendingTraceCountSignal.value);
  const selectedIds = $derived(selectedTraceIdsSignal.value);
  const selectedCount = $derived(selectedTraceCountSignal.value);

  let query = $state('');
  let statusFilter = $state<StatusFilter>('all');
  let minDuration = $state(0);
  let searchRef: HTMLInputElement | null = $state(null);
  let showImport = $state(false);

  const hasSelection = $derived(selectedCount > 0);

  // Keyboard shortcuts for trace list. `?` help is owned globally by Layout.
  $effect(() => {
    if (selectedTrace) return;
    const handleKeydown = (e: KeyboardEvent) => {
      if (helpShortcutsSignal.value || showImport) return; // a modal is open
      if (e.key === '/' && !isInputFocused()) {
        e.preventDefault();
        searchRef?.focus();
        return;
      }
      if (e.key === 'Escape') {
        if (hasSelection) {
          clearTraceSelection();
        } else if (document.activeElement === searchRef) {
          query = '';
        }
      }
      if (e.key === 'a' && (e.metaKey || e.ctrlKey) && !isInputFocused()) {
        e.preventDefault();
        selectAllTraces();
      }
    };
    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });

  const filtered = $derived.by(() =>
    traces.filter((trace) =>
      traceMatches(trace, query, statusFilter, minDuration),
    ),
  );

  // Keyboard row navigation over the filtered list.
  let listRef: HTMLDivElement | undefined = $state();

  const nav = useListKeyboardNav({
    count: () => filtered.length,
    onActivate: (index) => {
      const trace = filtered[index];
      if (trace) setSelectedTrace(trace.traceId);
    },
    scrollToIndex: (index) =>
      queueMicrotask(() => {
        listRef
          ?.querySelector<HTMLElement>(`[data-row-index="${index}"]`)
          ?.scrollIntoView({ block: 'nearest' });
      }),
  });

  function handleExportSelected() {
    const selected = traces.filter((t) => selectedIds.has(t.traceId));
    if (selected.length > 0) downloadTracesAsJson(selected);
  }

  const isFiltered = $derived(
    query.length > 0 || statusFilter !== 'all' || minDuration > 0,
  );
  const allFilteredSelected = $derived(
    filtered.length > 0 && filtered.every((t) => selectedIds.has(t.traceId)),
  );
</script>

{#snippet sortHeader(
  label: string,
  sortKey: TraceSortKey,
  align?: 'end',
  extraClass?: string,
)}
  {@const active = sort.key === sortKey}
  <button
    onclick={() => setTraceSort(sortKey)}
    class={cn(
      'flex items-center gap-1 min-w-0 transition-colors hover:text-fg-muted',
      active ? 'text-fg-muted' : 'text-fg-subtle',
      align === 'end' && 'justify-end',
      extraClass,
    )}
    title={`Sort by ${label.toLowerCase()}`}
  >
    <span class="truncate">{label}</span>
    {#if active}
      {#if sort.dir === 'asc'}
        <ArrowUp size={11} class="flex-shrink-0" />
      {:else}
        <ArrowDown size={11} class="flex-shrink-0" />
      {/if}
    {/if}
  </button>
{/snippet}

{#snippet traceRow(trace: TraceData, isSelected: boolean, index: number)}
  {@const isError = trace.status === 'ERROR'}
  {@const sc = serviceColor(trace.service || 'unknown')}
  {@const isCursor = nav.cursor === index}
  <div
    class={cn(
      'group trace-grid px-4 py-2 border-b border-line-subtle cursor-pointer transition-colors',
      isSelected
        ? 'bg-accent/10'
        : isError
          ? 'bg-danger-bg/40 hover:bg-danger-bg/70'
          : 'hover:bg-hover',
      isCursor && 'ring-1 ring-inset ring-accent bg-accent/10',
    )}
    role="option"
    aria-selected={isCursor}
    tabindex="-1"
    data-row-index={index}
    data-focus-inset
    onclick={() => {
      nav.cursor = index;
      setSelectedTrace(trace.traceId);
    }}
    onkeydown={activateOnKey(() => setSelectedTrace(trace.traceId))}
  >
    <!-- Select. stopPropagation lives on the checkbox (interactive) so toggling
         it doesn't also fire the row's select handler. -->
    <label class="cursor-pointer flex items-center">
      <input
        type="checkbox"
        checked={isSelected}
        onclick={(e) => e.stopPropagation()}
        onchange={() => toggleTraceSelection(trace.traceId)}
        class="w-3.5 h-3.5 rounded border-line text-accent"
      />
    </label>

    <!-- Service pill -->
    <span
      class="text-[11px] font-medium px-2 py-0.5 rounded truncate"
      style="background-color: {sc.fill}; color: {sc.stroke};"
      title={trace.service || 'unknown'}
    >
      {trace.service || 'unknown'}
    </span>

    <!-- Operation -->
    <div class="flex items-center gap-1.5 min-w-0">
      {#if isError}
        <AlertCircle size={13} class="text-danger flex-shrink-0" />
      {/if}
      <span class="truncate text-sm text-fg" title={trace.rootSpan.name}>
        {trace.rootSpan.name || 'unknown'}
      </span>
      <!-- One copy affordance per row (trace ID — the primary thing to grab).
           Correlation ID copy lives in the trace detail to avoid two identical
           icons cluttering the row. -->
      <CopyButton
        value={trace.traceId}
        label="Copy trace ID"
        class="opacity-0 group-hover:opacity-100 focus-visible:opacity-100 transition-opacity"
      />
    </div>

    <!-- Duration -->
    <span class="font-mono text-xs text-fg-muted text-right tabular-nums">
      {formatDuration(trace.duration)}
    </span>

    <!-- Span count -->
    <span
      class="trace-col-spans font-mono text-xs text-fg-subtle text-right tabular-nums"
    >
      {trace.spans.length}
    </span>

    <!-- Time -->
    <span class="trace-col-time font-mono text-[11px] text-fg-subtle truncate">
      {formatTimestamp(trace.startTime)}
    </span>

    <!-- Status -->
    <span
      class={cn(
        'text-[10px] font-semibold px-1.5 py-0.5 rounded justify-self-start',
        isError
          ? 'bg-danger-bg text-danger'
          : trace.status === 'OK'
            ? 'bg-success-bg text-success'
            : 'bg-hover text-fg-muted',
      )}
    >
      {trace.status}
    </span>

    <ChevronRight size={15} class="text-fg-subtle justify-self-end" />
  </div>
{/snippet}

{#if selectedTrace}
  <TraceDetailView trace={selectedTrace} />
{:else}
  <div class="flex flex-col h-full">
    <!-- Header -->
    <div
      class="px-4 py-3 border-b border-line flex items-center justify-between gap-2"
    >
      <h3 class="text-sm font-semibold flex items-center gap-2 text-fg">
        <Database size={16} />
        Traces ({isFiltered
          ? `${filtered.length} of ${traces.length}`
          : traces.length})
        {#if hasSelection}
          <span class="text-xs font-normal text-accent">
            ({selectedCount} selected)
          </span>
        {/if}
      </h3>
      <div class="flex items-center gap-1">
        <!-- Bulk actions bar -->
        {#if hasSelection}
          <div class="flex items-center gap-1 mr-2 px-2 border-r border-line">
            <button
              onclick={handleExportSelected}
              class="flex items-center gap-1 px-2 py-1 text-xs rounded bg-accent/10 text-accent hover:bg-accent/20 transition-colors"
              title="Export selected traces"
            >
              <Download size={12} />
              Export ({selectedCount})
            </button>
            <button
              onclick={deleteSelectedTraces}
              class="flex items-center gap-1 px-2 py-1 text-xs rounded bg-danger-bg text-danger hover:bg-danger-bg/80 transition-colors"
              title="Delete selected traces"
            >
              <Trash2 size={12} />
              Delete
            </button>
          </div>
        {/if}
        <button
          onclick={togglePaused}
          class={cn(
            'flex items-center gap-1 px-2 py-1 text-xs rounded transition-colors',
            paused
              ? 'bg-warning-bg text-warning hover:bg-warning-bg/80'
              : 'hover:bg-hover text-fg-muted',
          )}
          title={paused ? 'Resume live tail' : 'Pause live tail'}
        >
          {#if paused}
            <Play size={12} />
          {:else}
            <Pause size={12} />
          {/if}
          {paused
            ? `Resume${pendingCount > 0 ? ` (+${pendingCount})` : ''}`
            : 'Pause'}
        </button>
        {#if paused && pendingCount > 0}
          <button
            onclick={dropPendingBuffer}
            class="px-2 py-1 text-xs rounded text-fg-subtle hover:bg-hover transition-colors"
            title="Drop buffered traces received while paused"
          >
            Drop buffer
          </button>
        {/if}
        <button
          onclick={() => (showImport = true)}
          class="p-1.5 hover:bg-hover rounded transition-colors"
          title="Import traces from file"
        >
          <Upload size={14} class="text-fg-subtle" />
        </button>
        {#if traces.length > 0}
          <button
            onclick={() => downloadTracesAsJson(traces)}
            class="p-1.5 hover:bg-hover rounded transition-colors"
            title="Export all traces as JSON"
          >
            <Download size={14} class="text-fg-subtle" />
          </button>
        {/if}
        <button
          onclick={() => openHelp(TRACE_LIST_SHORTCUTS)}
          class="p-1.5 hover:bg-hover rounded transition-colors"
          title="Keyboard shortcuts (?)"
        >
          <HelpCircle size={14} class="text-fg-subtle" />
        </button>
      </div>
    </div>

    <!-- Filter bar -->
    <div class="px-4 py-2 border-b border-line flex items-center gap-2">
      <SearchInput
        bind:value={query}
        bind:ref={searchRef}
        placeholder="Filter by service, span, trace id…"
      />
      <select
        value={statusFilter}
        onchange={(event) =>
          (statusFilter = (event.currentTarget as HTMLSelectElement)
            .value as StatusFilter)}
        class="text-xs border border-line rounded px-1.5 py-1 bg-surface text-fg-muted"
      >
        <option value="all">All</option>
        <option value="error">Errors</option>
        <option value="ok">OK</option>
      </select>
      <!-- Min duration -->
      <div
        class="flex items-center text-xs text-fg-subtle flex-shrink-0"
        title="Only show traces at least this slow"
      >
        <span class="mr-1">≥</span>
        <input
          type="number"
          min={0}
          step={50}
          value={minDuration || ''}
          placeholder="0"
          oninput={(event) =>
            (minDuration =
              Number((event.currentTarget as HTMLInputElement).value) || 0)}
          class="w-14 px-1 py-1 rounded border border-line bg-surface text-fg-muted focus:outline-none"
        />
        <span class="ml-1">ms</span>
      </div>
    </div>

    <!-- Traces list — dense, sortable, container-responsive -->
    <div
      bind:this={listRef}
      class="trace-list-container flex-1 overflow-auto focus:outline-none"
      role="listbox"
      aria-label="Traces"
      tabindex="0"
      onkeydown={nav.onKeyDown}
    >
      {#if traces.length === 0}
        <div class="text-center text-fg-subtle text-sm py-12">
          <p class="mb-3">No traces yet. Waiting for data…</p>
        </div>
      {:else if filtered.length === 0}
        <div class="text-center text-fg-subtle text-sm py-12">
          No traces match the current filter.
        </div>
      {:else}
        <div>
          <!-- Column header -->
          <div
            class="trace-grid sticky top-0 z-10 px-4 py-2 border-b border-line bg-subtle text-[11px] font-semibold uppercase tracking-wide text-fg-subtle"
          >
            <label
              class="cursor-pointer flex items-center"
              title={allFilteredSelected ? 'Clear selection' : 'Select all'}
            >
              <input
                type="checkbox"
                checked={allFilteredSelected}
                onclick={(e) => e.stopPropagation()}
                onchange={() =>
                  allFilteredSelected
                    ? clearTraceSelection()
                    : selectAllTraces()}
                class="w-3.5 h-3.5 rounded border-line text-accent"
              />
            </label>
            {@render sortHeader('Service', 'service')}
            {@render sortHeader('Operation', 'name')}
            {@render sortHeader('Duration', 'duration', 'end')}
            {@render sortHeader('Spans', 'spans', 'end', 'trace-col-spans')}
            {@render sortHeader('Time', 'time', undefined, 'trace-col-time')}
            {@render sortHeader('Status', 'status')}
            <span></span>
          </div>

          {#each filtered as trace, index (trace.traceId)}
            {@render traceRow(trace, selectedIds.has(trace.traceId), index)}
          {/each}
        </div>
      {/if}
    </div>

    {#if showImport}
      <TraceImportModal
        onclose={() => (showImport = false)}
        onimport={async (file: File) => {
          try {
            const text = await readFileAsText(file);
            const result = parseImportedJson(text);
            if (result.success && result.traces.length > 0) {
              importTraces(result.traces);
              return {
                imported: result.traces.length,
                errors: [],
                warnings: result.warnings,
              };
            }
            return {
              imported: 0,
              errors: result.errors,
              warnings: result.warnings,
            };
          } catch (err) {
            return { imported: 0, errors: [String(err)], warnings: [] };
          }
        }}
      />
    {/if}
  </div>
{/if}
