// packages/autotel-devtools/src/widget/components/WaterfallView.tsx
/**
 * Waterfall visualization for trace spans
 * Shows spans in a timeline view with bars representing duration
 */

import { h } from 'preact';
import { useState, useMemo } from 'preact/hooks';
import { AlertCircle, ChevronDown, ChevronRight, Info } from 'lucide-preact';
import { cn } from '../utils/cn';
import { formatDuration } from '../utils';
import type { TraceData, SpanData } from '../types';

interface WaterfallViewProps {
  trace: TraceData;
  onSpanSelect?: (span: SpanData | null) => void;
  selectedSpanId?: string | null;
}

interface SpanNode {
  span: SpanData;
  children: SpanNode[];
  depth: number;
}

/**
 * Build a tree structure from flat spans array
 */
function buildSpanTree(spans: SpanData[]): SpanNode[] {
  const spanMap = new Map<string, SpanNode>();
  const roots: SpanNode[] = [];

  // Create nodes for all spans
  for (const span of spans) {
    spanMap.set(span.spanId, { span, children: [], depth: 0 });
  }

  // Build tree structure
  for (const span of spans) {
    const node = spanMap.get(span.spanId)!;
    if (span.parentSpanId) {
      const parent = spanMap.get(span.parentSpanId);
      if (parent) {
        parent.children.push(node);
        node.depth = parent.depth + 1;
      } else {
        // Parent not found, treat as root
        roots.push(node);
      }
    } else {
      roots.push(node);
    }
  }

  // Sort children by start time
  const sortChildren = (nodes: SpanNode[]) => {
    nodes.sort((a, b) => a.span.startTime - b.span.startTime);
    for (const node of nodes) sortChildren(node.children);
  };
  sortChildren(roots);

  return roots;
}

/**
 * Flatten tree to array while preserving depth info, skipping children of collapsed nodes
 */
function flattenTree(nodes: SpanNode[], collapsed: Set<string>): SpanNode[] {
  const result: SpanNode[] = []
  const traverse = (node: SpanNode) => {
    result.push(node)
    if (!collapsed.has(node.span.spanId)) {
      node.children.forEach(traverse)
    }
  }
  nodes.forEach(traverse)
  return result
}

/**
 * Count all descendants of a node
 */
function countDescendants(node: SpanNode): number {
  let count = node.children.length
  for (const child of node.children) count += countDescendants(child)
  return count
}

/**
 * Calculate timing info for waterfall bar positioning
 */
function calculateTimingInfo(span: SpanData, trace: TraceData) {
  const traceStart = trace.startTime;
  const traceDuration = trace.duration || 1; // Prevent division by zero

  const offsetMs = span.startTime - traceStart;
  const offsetPercent = (offsetMs / traceDuration) * 100;
  const widthPercent = (span.duration / traceDuration) * 100;

  return {
    offsetMs,
    offsetPercent: Math.max(0, Math.min(100, offsetPercent)),
    widthPercent: Math.max(0.5, Math.min(100 - offsetPercent, widthPercent)), // Min 0.5% for visibility
  };
}

/**
 * Get color for span kind
 */
function getSpanKindColor(kind: SpanData['kind']): string {
  switch (kind) {
    case 'SERVER': {
      return 'bg-blue-500';
    }
    case 'CLIENT': {
      return 'bg-green-500';
    }
    case 'PRODUCER': {
      return 'bg-purple-500';
    }
    case 'CONSUMER': {
      return 'bg-orange-500';
    }
    case 'INTERNAL':
    default: {
      return 'bg-gray-500';
    }
  }
}

/**
 * Get lighter color for span kind (hover state)
 */
function getSpanKindColorLight(kind: SpanData['kind']): string {
  switch (kind) {
    case 'SERVER': {
      return 'bg-blue-400';
    }
    case 'CLIENT': {
      return 'bg-green-400';
    }
    case 'PRODUCER': {
      return 'bg-purple-400';
    }
    case 'CONSUMER': {
      return 'bg-orange-400';
    }
    case 'INTERNAL':
    default: {
      return 'bg-gray-400';
    }
  }
}

export function WaterfallView({
  trace,
  onSpanSelect,
  selectedSpanId,
}: WaterfallViewProps) {
  const [collapsed, setCollapsed] = useState(new Set<string>());

  // Build span tree and flatten (skipping children of collapsed nodes)
  const spanTree = useMemo(() => buildSpanTree(trace.spans), [trace.spans]);
  const visibleSpans = useMemo(() => flattenTree(spanTree, collapsed), [spanTree, collapsed]);

  const toggleCollapse = (spanId: string) => {
    setCollapsed(prev => {
      const next = new Set(prev)
      if (next.has(spanId)) next.delete(spanId)
      else next.add(spanId)
      return next
    })
  }

  const hasChildren = (spanId: string) => {
    return trace.spans.some((s) => s.parentSpanId === spanId);
  };

  // Generate time markers
  const timeMarkers = useMemo(() => {
    const duration = trace.duration || 1;
    const markers: { percent: number; label: string }[] = [];
    const numMarkers = 5;

    for (let i = 0; i <= numMarkers; i++) {
      const percent = (i / numMarkers) * 100;
      const time = (i / numMarkers) * duration;
      markers.push({
        percent,
        label: formatDuration(time),
      });
    }
    return markers;
  }, [trace.duration]);

  return (
    <div className="flex flex-col h-full">
      {/* Timeline header with time markers */}
      <div className="flex border-b border-gray-200 bg-gray-50 text-xs text-gray-500">
        <div className="w-[200px] shrink-0 px-3 py-2 font-medium text-gray-700">
          Span Name
        </div>
        <div className="flex-1 relative py-2">
          {timeMarkers.map((marker, idx) => (
            <div
              key={idx}
              className="absolute text-[10px]"
              style={{
                left: `${marker.percent}%`,
                transform: 'translateX(-50%)',
              }}
            >
              {marker.label}
            </div>
          ))}
        </div>
        <div className="w-[80px] shrink-0 px-2 py-2 text-right font-medium text-gray-700">
          Duration
        </div>
      </div>

      {/* Timeline grid lines */}
      <div className="flex-1 overflow-auto relative">
        {/* Grid lines behind content */}
        <div
          className="absolute inset-0 pointer-events-none"
          style={{ left: '200px', right: '80px' }}
        >
          {timeMarkers.map((marker, idx) => (
            <div
              key={idx}
              className="absolute top-0 bottom-0 border-l border-gray-100"
              style={{ left: `${marker.percent}%` }}
            />
          ))}
        </div>

        {/* Span rows */}
        <div className="relative">
          {visibleSpans.map((node) => (
            <WaterfallRow
              key={node.span.spanId}
              node={node}
              trace={trace}
              isSelected={selectedSpanId === node.span.spanId}
              isCollapsed={collapsed.has(node.span.spanId)}
              hasChildren={hasChildren(node.span.spanId)}
              onSelect={() => onSpanSelect?.(node.span)}
              onToggleCollapse={() => toggleCollapse(node.span.spanId)}
            />
          ))}
        </div>
      </div>

      {/* Legend */}
      <div className="flex items-center gap-4 px-3 py-2 border-t border-gray-200 bg-gray-50 text-xs">
        <span className="text-gray-500 font-medium">Kind:</span>
        {(
          ['SERVER', 'CLIENT', 'INTERNAL', 'PRODUCER', 'CONSUMER'] as const
        ).map((kind) => (
          <div key={kind} className="flex items-center gap-1">
            <div className={cn('w-3 h-3 rounded-sm', getSpanKindColor(kind))} />
            <span className="text-gray-600">{kind}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

interface WaterfallRowProps {
  node: SpanNode;
  trace: TraceData;
  isSelected: boolean;
  isCollapsed: boolean;
  hasChildren: boolean;
  onSelect: () => void;
  onToggleCollapse: () => void;
}

function WaterfallRow({
  node,
  trace,
  isSelected,
  isCollapsed,
  hasChildren,
  onSelect,
  onToggleCollapse,
}: WaterfallRowProps) {
  const { span } = node;
  const timing = calculateTimingInfo(span, trace);
  const isError = span.status.code === 'ERROR';
  const hasEvents = span.events && span.events.length > 0;

  return (
    <div
      className={cn(
        'flex items-center border-b border-gray-100 hover:bg-blue-50/50 cursor-pointer transition-colors',
        isSelected && 'bg-blue-50 hover:bg-blue-100/50',
        isError && 'bg-red-50/30 hover:bg-red-50/50',
      )}
      onClick={onSelect}
    >
      {/* Span name column */}
      <div
        className="w-[200px] shrink-0 px-2 py-2 flex items-center gap-1 min-w-0"
        style={{ paddingLeft: `${8 + node.depth * 16}px` }}
      >
        {/* Collapse/expand button */}
        {hasChildren ? (
          <button
            onClick={(e) => {
              e.stopPropagation();
              onToggleCollapse();
            }}
            className="p-0.5 hover:bg-gray-200 rounded flex-shrink-0"
          >
            {isCollapsed ? (
              <ChevronRight size={12} className="text-gray-500" />
            ) : (
              <ChevronDown size={12} className="text-gray-500" />
            )}
          </button>
        ) : (
          <div className="w-4" />
        )}

        {/* Error indicator */}
        {isError && (
          <AlertCircle size={12} className="text-red-500 flex-shrink-0" />
        )}

        {/* Events indicator */}
        {hasEvents && (
          <Info size={10} className="text-blue-500 flex-shrink-0" />
        )}

        {/* Span name */}
        <span
          className={cn(
            'text-xs truncate',
            isError ? 'text-red-700' : 'text-gray-900',
          )}
          title={span.name}
        >
          {span.name || 'unknown'}
        </span>

        {/* Collapsed children count */}
        {isCollapsed && node.children.length > 0 && (
          <span className="text-xs text-gray-400 ml-1">(+{countDescendants(node)})</span>
        )}
      </div>

      {/* Timeline bar column */}
      <div className="flex-1 py-2 px-1 relative h-8">
        <div
          className={cn(
            'absolute h-5 rounded-sm transition-colors group',
            isError ? 'bg-red-500' : getSpanKindColor(span.kind),
            isSelected &&
              (isError ? 'bg-red-600' : getSpanKindColorLight(span.kind)),
          )}
          style={{
            left: `${timing.offsetPercent}%`,
            width: `${timing.widthPercent}%`,
            top: '50%',
            transform: 'translateY(-50%)',
            minWidth: '4px',
          }}
          title={`${span.name}: ${formatDuration(span.duration)}`}
        >
          {/* Show duration label inside bar if wide enough */}
          {timing.widthPercent > 10 && (
            <span className="absolute inset-0 flex items-center justify-center text-[10px] text-white font-medium">
              {formatDuration(span.duration)}
            </span>
          )}

          {/* Inline event markers */}
          {span.events && span.events.length > 0 && span.events.map((event, idx) => {
            const eventPos = trace.duration > 0
              ? ((event.timestamp - trace.startTime) / trace.duration) * 100
              : 0
            return (
              <div
                key={idx}
                className={cn(
                  'absolute top-1/2 -translate-y-1/2 w-2 h-2 rounded-full border border-white z-10',
                  event.name === 'exception' ? 'bg-red-500' : 'bg-yellow-500',
                )}
                style={{ left: `${Math.min(Math.max(eventPos, 0), 100)}%` }}
                title={`${event.name} at ${formatDuration(event.timestamp - trace.startTime)}`}
              />
            )
          })}
        </div>
      </div>

      {/* Duration column */}
      <div className="w-[80px] shrink-0 px-2 py-2 text-right">
        <span
          className={cn(
            'text-xs font-mono',
            isError ? 'text-red-600' : 'text-gray-600',
          )}
        >
          {formatDuration(span.duration)}
        </span>
      </div>
    </div>
  );
}

export default WaterfallView;

// packages/autotel-devtools/src/widget/components/WaterfallView.svelte
<script lang="ts" module>
  import type { SpanData } from '../types';
  import type { SpanNode } from './WaterfallRow.svelte';

  /**
   * Build a tree structure from flat spans array.
   * Handles cycle detection and orphan spans with phantom placeholder nodes.
   */
  function buildSpanTree(spans: SpanData[]): SpanNode[] {
    const spanMap = new Map<string, SpanNode>();
    const roots: SpanNode[] = [];
    const orphansByParent = new Map<string, SpanNode[]>();

    // Create nodes for all spans
    for (const span of spans) {
      spanMap.set(span.spanId, { span, children: [], depth: 0 });
    }

    // Build tree structure
    for (const span of spans) {
      const node = spanMap.get(span.spanId)!;
      if (span.parentSpanId) {
        const parent = spanMap.get(span.parentSpanId);
        if (parent) {
          parent.children.push(node);
        } else {
          // Parent not found — group orphan under missing parent id
          const orphans = orphansByParent.get(span.parentSpanId) || [];
          orphans.push(node);
          orphansByParent.set(span.parentSpanId, orphans);
        }
      } else {
        roots.push(node);
      }
    }

    // Set depths and detect cycles via visited set
    const setDepth = (
      node: SpanNode,
      depth: number,
      visited: Set<string> = new Set(),
    ) => {
      if (visited.has(node.span.spanId)) return; // Cycle detected
      visited.add(node.span.spanId);
      node.depth = depth;
      for (const child of node.children) {
        setDepth(child, depth + 1, new Set(visited));
      }
    };

    // Build phantom placeholder nodes for orphaned children
    for (const [missingParentId, orphanNodes] of orphansByParent) {
      orphanNodes.sort((a, b) => a.span.startTime - b.span.startTime);
      const startTime = Math.min(...orphanNodes.map((n) => n.span.startTime));
      const endTime = Math.max(...orphanNodes.map((n) => n.span.endTime));

      // Find any existing span that knows about this missing parent id
      const referencingSpan = spans.find((s) => s.spanId === missingParentId);

      const phantomSpan: SpanData = {
        spanId: missingParentId,
        traceId: orphanNodes[0].span.traceId,
        parentSpanId: referencingSpan?.parentSpanId || undefined,
        name: '(missing)',
        kind: 'INTERNAL',
        startTime,
        endTime,
        duration: endTime - startTime,
        attributes: {},
        status: { code: 'UNSET' },
        events: [],
      };
      const phantomNode: SpanNode = {
        span: phantomSpan,
        children: orphanNodes,
        depth: 0,
      };
      roots.push(phantomNode);
    }

    // Set depths for all root nodes
    for (const root of roots) {
      setDepth(root, 0);
    }

    // Sort children recursively by start time
    const sortChildren = (nodes: SpanNode[]) => {
      nodes.sort((a, b) => a.span.startTime - b.span.startTime);
      for (const node of nodes) sortChildren(node.children);
    };
    sortChildren(roots);

    return roots;
  }

  /**
   * Flatten tree to array while preserving depth info, skipping children of collapsed nodes
   */
  function flattenTree(nodes: SpanNode[], collapsed: Set<string>): SpanNode[] {
    const result: SpanNode[] = [];
    const traverse = (node: SpanNode) => {
      result.push(node);
      if (!collapsed.has(node.span.spanId)) {
        node.children.forEach(traverse);
      }
    };
    nodes.forEach(traverse);
    return result;
  }
</script>

<script lang="ts">
  /**
   * Waterfall visualization for trace spans
   * Shows spans in a timeline view with bars representing duration
   */
  import { Zap } from '@lucide/svelte';
  import { cn } from '../utils/cn';
  import { formatDuration } from '../utils';
  import { isInputFocused } from '../utils/keyboard';
  import { computeCriticalPath } from '../utils/spanAnalysis';
  import { helpShortcutsSignal } from '../store.svelte';
  import type { TraceData } from '../types';
  import WaterfallRow, { getSpanKindColor } from './WaterfallRow.svelte';

  interface Props {
    trace: TraceData;
    onSpanSelect?: (span: SpanData | null) => void;
    selectedSpanId?: string | null;
  }

  let { trace, onSpanSelect, selectedSpanId = null }: Props = $props();

  const GRID_LINES_STYLE = 'left: 200px; right: 80px;';

  let collapsed = $state(new Set<string>());
  let showCritical = $state(true);
  let markersEl: HTMLDivElement | undefined = $state();
  let markersWidth = $state(0);

  const criticalPath = $derived.by(() => computeCriticalPath(trace.spans));

  // Track the timeline column width so the number of axis labels adapts to the
  // available space (the detail pane is resizable / responsive).
  $effect(() => {
    const el = markersEl;
    if (!el || typeof ResizeObserver === 'undefined') return;
    const ro = new ResizeObserver((entries) => {
      markersWidth = entries[0].contentRect.width;
    });
    ro.observe(el);
    return () => ro.disconnect();
  });

  // Build span tree and flatten (skipping children of collapsed nodes)
  const spanTree = $derived.by(() => buildSpanTree(trace.spans));
  const visibleSpans = $derived.by(() => flattenTree(spanTree, collapsed));

  // Arrow key navigation
  const handleKeydown = (e: KeyboardEvent) => {
    if (helpShortcutsSignal.value || isInputFocused()) return;
    if (e.key !== 'ArrowUp' && e.key !== 'ArrowDown' && e.key !== 'Enter')
      return;

    e.preventDefault();
    const currentIdx = visibleSpans.findIndex(
      (n) => n.span.spanId === selectedSpanId,
    );
    let nextIdx: number;

    if (e.key === 'ArrowUp') {
      nextIdx = currentIdx > 0 ? currentIdx - 1 : visibleSpans.length - 1;
    } else if (e.key === 'ArrowDown') {
      nextIdx = currentIdx < visibleSpans.length - 1 ? currentIdx + 1 : 0;
    } else {
      // Enter — if a span is focused, select it; otherwise select first
      if (currentIdx >= 0) {
        onSpanSelect?.(visibleSpans[currentIdx].span);
        return;
      }
      nextIdx = 0;
    }

    const next = visibleSpans[nextIdx];
    if (next) {
      onSpanSelect?.(next.span);
      // Scroll the row into view
      const el = document.getElementById(`waterfall-row-${next.span.spanId}`);
      el?.scrollIntoView({ block: 'nearest' });
    }
  };

  $effect(() => {
    // Re-subscribe when visibleSpans / selectedSpanId change (matches source deps).
    void visibleSpans;
    void selectedSpanId;
    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });

  const toggleCollapse = (spanId: string) => {
    const next = new Set(collapsed);
    if (next.has(spanId)) next.delete(spanId);
    else next.add(spanId);
    collapsed = next;
  };

  const hasChildren = (spanId: string) => {
    return trace.spans.some((s) => s.parentSpanId === spanId);
  };

  // Generate time markers. One label per ~90px (min 2, max 8 segments), so
  // labels never collide in a narrow column. Falls back to 5 before measuring.
  const timeMarkers = $derived.by(() => {
    const duration = trace.duration || 1;
    const segments =
      markersWidth > 0
        ? Math.min(8, Math.max(2, Math.floor(markersWidth / 90)))
        : 5;
    const markers: {
      percent: number;
      label: string;
      align: 'start' | 'mid' | 'end';
    }[] = [];

    for (let i = 0; i <= segments; i++) {
      markers.push({
        percent: (i / segments) * 100,
        label: formatDuration((i / segments) * duration),
        align: i === 0 ? 'start' : i === segments ? 'end' : 'mid',
      });
    }
    return markers;
  });

  const SPAN_KINDS = [
    'SERVER',
    'CLIENT',
    'INTERNAL',
    'PRODUCER',
    'CONSUMER',
  ] as const;
</script>

<div class="flex flex-col h-full">
  <!-- Timeline header with time markers -->
  <div class="flex border-b border-line bg-subtle text-xs text-fg-subtle">
    <div class="w-[200px] shrink-0 px-3 py-2 font-medium text-fg-muted">
      Span Name
    </div>
    <div bind:this={markersEl} class="flex-1 relative py-2">
      {#each timeMarkers as marker, idx (idx)}
        <div
          class="absolute text-[10px] whitespace-nowrap tabular-nums"
          style={`left: ${marker.percent}%; transform: ${
            marker.align === 'start'
              ? 'translateX(0)'
              : marker.align === 'end'
                ? 'translateX(-100%)'
                : 'translateX(-50%)'
          };`}
        >
          {marker.label}
        </div>
      {/each}
    </div>
    <div
      class="w-[80px] shrink-0 px-2 py-2 text-right font-medium text-fg-muted"
    >
      Duration
    </div>
  </div>

  <!-- Timeline grid lines -->
  <div class="flex-1 overflow-auto relative">
    <!-- Grid lines behind content -->
    <div class="absolute inset-0 pointer-events-none" style={GRID_LINES_STYLE}>
      {#each timeMarkers as marker, idx (idx)}
        <div
          class="absolute top-0 bottom-0 border-l border-line-subtle"
          style={`left: ${marker.percent}%;`}
        ></div>
      {/each}
    </div>

    <!-- Span rows -->
    <div class="relative">
      {#each visibleSpans as node (node.span.spanId)}
        <WaterfallRow
          {node}
          {trace}
          isSelected={selectedSpanId === node.span.spanId}
          isCollapsed={collapsed.has(node.span.spanId)}
          hasChildren={hasChildren(node.span.spanId)}
          isCritical={showCritical && criticalPath.has(node.span.spanId)}
          onSelect={() => onSpanSelect?.(node.span)}
          onToggleCollapse={() => toggleCollapse(node.span.spanId)}
        />
      {/each}
    </div>
  </div>

  <!-- Legend -->
  <div
    class="flex items-center gap-4 px-3 py-2 border-t border-line bg-subtle text-xs"
  >
    <span class="text-fg-subtle font-medium">Kind:</span>
    {#each SPAN_KINDS as kind (kind)}
      <div class="flex items-center gap-1">
        <div class={cn('w-3 h-3 rounded-sm', getSpanKindColor(kind))}></div>
        <span class="text-fg-muted">{kind}</span>
      </div>
    {/each}
    <button
      onclick={() => (showCritical = !showCritical)}
      class={cn(
        'ml-auto flex items-center gap-1 px-1.5 py-0.5 rounded border transition-colors',
        showCritical
          ? 'bg-amber-100 text-amber-800 border-amber-300'
          : 'text-fg-subtle border-line hover:bg-hover',
      )}
      title="Highlight the spans that determine total trace latency"
    >
      <Zap size={11} />
      Critical path
    </button>
  </div>
</div>
